name = "cmumaps"
github-team = "cmu-maps"
leads = [
    "Yuxiang-Huang",
    "luke992",
]
members = [
    "ellylai",
    "Nicolapps",
    "JettChenT",
    "SLin24",
    "Richard-31415",
    "kath45823"
]
repos = [
    "ScottyLabs/cmumaps",
]
