name: "cmumaps"

services:
  postgres:
    image: postgres:17
    container_name: cmumaps-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donotuseinprod
      POSTGRES_DB: cmumaps
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
