name: Sync

on:
  push:
    branches:
      - main
      - staging

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    env:
      SYNC_GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Sync Script
        run: cd governance && pip3 install -r requirements.txt && python3 -m scripts.sync
